# This file is where you define your pipelines. You can define multiple.
# For more information on multiple pipelines, see the documentation:
#   https://www.elastic.co/guide/en/logstash/current/multiple-pipelines.html

- pipeline.id: siuc-kpi-graph
  path.config: "/usr/share/logstash/pipeline/siuc-kpi-graph.conf"
  pipeline.workers: 1
  queue.type: persisted
  pipeline.batch.size: 125
  pipeline.batch.delay: 500